on:
  push:
    branches:
      - 'main'
      - 'spec-test-*'

permissions:
  contents: read

jobs:
  sync-acceptance:
    if: github.repository == 'hashicorp/vagrant'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Code Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Sync Acceptance Testing Repository
        run: ./.ci/sync.sh
        working-directory: ${{github.workspace}}
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          HASHIBOT_USERNAME: ${{ secrets.HASHIBOT_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
