on:
  push:
    branches:
      - main
      - 'test-*'
    paths:
      - 'builtin/**'
      - 'cmd/**'
      - 'internal/**'
      - '.github/workflows**'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches:
      - main
    paths:
      - 'builtin/**'
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read

jobs:
  unit-tests-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['^1.16']
        ruby: ['3.0', '3.1']
    name: Vagrant unit tests on Go
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{matrix.go}}
      - name: Setup Ruby
        uses: ruby/setup-ruby@8a45918450651f5e4784b6031db26f4b9f76b251 # v1.150.0
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Vet
        run:  go vet -mod=mod ./...
      - name: Test
        run:  go test -mod=mod ./...
