on:
  push:
    tags: 'v*'

permissions:
  contents: read

jobs:
  trigger-release:
    if: github.repository == 'hashicorp/vagrant'
    name: Trigger Installers Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Trigger Build
        run: ./.ci/release
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
