on:
  push:
    branches:
      - main
      - 'test-*'
    paths:
      - 'bin/**'
      - 'lib/**'
      - 'plugins/**'
      - 'test/**'
      - 'templates/**'
      - 'Gemfile'
      - 'vagrant.gemspec'
      - 'Rakefile'
  pull_request:
    branches:
      - main
    paths:
      - 'bin/**'
      - 'lib/**'
      - 'plugins/**'
      - 'test/**'
      - 'Gemfile'
      - 'templates/**'
      - 'vagrant.gemspec'
      - 'Rakefile'

permissions:
  contents: read

jobs:
  unit-tests-ruby:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        ruby: [ '3.0', '3.1', '3.2' ]
    name: Vagrant unit tests on Ruby ${{ matrix.ruby }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Setup Ruby
        uses: ruby/setup-ruby@8a45918450651f5e4784b6031db26f4b9f76b251 # v1.150.0
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: install dependencies
        run: sudo apt -y install libarchive-tools
      - name: Run Tests
        run: bundle exec rake test:unit
